name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pip install poetry

      - name: Install Firefox and Geckodriver
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox
          GECKODRIVER_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep tag_name | cut -d '"' -f 4)
          wget https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
          tar -xzf geckodriver-*.tar.gz
          sudo mv geckodriver /usr/local/bin/

      - name: Verify Firefox and Geckodriver
        run: |
          which firefox && firefox --version
          which geckodriver && geckodriver --versio


      - name: Install dependencies
        run: poetry install

      - name: Run Robot Framework tests
        run: poetry run bash run_robot_tests.sh

      - name: Upload Robot Framework reports
        uses: actions/upload-artifact@v4
        with:
          name: robot-reports
          path: |
            output.xml
            log.html
            report.html
